name: ci
on:
  pull-requests:
    branches: [dev, main]
  jobs:
    build_and_test:
      runs-on: macos-latest
      steps:
        - name: code-checkout
          uses: actions/checkout@v3
        - name: build
        run: |
          mkdir build
          cd ./build
          cmake ../
          cmake --build .


